# Travis CI configuration file
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"

branches:
  except:
    - experimental
    - /^appveyor.*$/

before_install:
  - echo "Package root:"
  - ls -1 $TRAVIS_BUILD_DIR
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip pytables numpy scipy tqdm pyyaml
  - conda activate test-env
  
# command to install dependencies
install:
  - which pip
  - pip install -r requirements.txt
  - echo "Done installing dependencies."
  
# command to run tests
script:
  nosetests --logging-level=INFO --nocapture;

