# Travis CI configuration file
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"

branches:
  except:
    - experimental
    - /^appveyor.*$/

before_install:
  - echo "Package root:"
  - ls -1 $TRAVIS_BUILD_DIR
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
  nosetests --logging-level=INFO --nocapture;

